#!python3

import sys
import os
import smartframe
from tcp_server import TcpServer
from http_server import HttpServer
import threading
import configparser
import io

# Load the configuration file
config = configparser.ConfigParser(allow_no_value=True)
config.read("/etc/py-smartframe/config.ini")

debug = config.getboolean('general', 'debug')   # Display traces if True
# Indicates if script are running on RPI or not (for debug purpose, PIR & FBI management should not be enables)
real_rpi_install = config.getboolean('general', 'real-rpi-install')
imgDir = config.get('general', 'img-dir')       # Photo directory

# HTTP server options
http_hostname = config.get('http-server', 'listening-ip')
http_port = config.getint('http-server', 'port')

# TCP server options
tcp_hostname = config.get('tcp-server', 'listening-ip')
tcp_port = config.getint('tcp-server', 'port')

# PIR management options
shutoff_delay = config.getint('pir', 'shutoff-delay')    # seconds
pir_pin = config.getint('pir', 'pin-number')

# instanciate sf API
sf = smartframe.SmartFrame(imgDir, real_rpi_install)


def start_pir():
    from pir_manager import PirManager
    pm = PirManager(pir_pin, shutoff_delay)
    pm.start()

def start_tcp_server():
    tcps = TcpServer(tcp_hostname, tcp_port, sf, debug)
    tcps.start()

def start_http_server():
    https = HttpServer(http_hostname, http_port, sf, debug)
    https.start()

def main():

    # enable PIR only if working with real RPI
    t1 = threading.Thread(target=start_pir, args=[])
    if real_rpi_install:
        t1.start()

    # enable TCP server
    t2 = threading.Thread(target=start_tcp_server, args=[])
    t2.start()

    # enable HTTP server
    t3 = threading.Thread(target=start_http_server, args=[])
    t3.start()


    # waiting for thread terminating
    if real_rpi_install:
        t1.join()

    t2.join()
    t3.join()
    print('Exiting...')



if __name__ == '__main__':
    try:
        main()
    except KeyboardInterrupt:
        print('Stopping py-smartframe')
        try:
            sys.exit(0)
        except SystemExit:
            os._exit(0)

